[package]
name = "file-size"
version = "1.0.2"
edition = "2018"
authors = ["dystroy <denys.seguret@gmail.com>"]
repository = "https://github.com/Canop/file-size"
description = "just a function formatting file sizes in 4 chars"
license = "MIT"

[dependencies]
